remote_theme: mmistakes/minimal-mistakes
title: Thinking out loud
description: My thoughts and experiences.
baseurl: ""
url: "https://evgeniy.tech"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Ensure posts use our `post` layout so the sidebar is injected on production builds
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"