# Local dev overrides: use gem-based theme for local builds and no remote-theme plugin
theme: minimal-mistakes-jekyll
baseurl: ""
plugins:
  - jekyll-include-cache

# Ensure posts use our `post` layout locally so the sidebar is injected
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
