remote_theme: mmistakes/minimal-mistakes
title: My Blog
description: A blog about my thoughts and experiences.
baseurl: "/www.trueadmin.ru"
url: "https://dev1l.github.io"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Ensure posts use our `post` layout so the sidebar is injected on production builds
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"